.TH HOSTGEN 8 "31 January 2024" "hostgen v0.3a"
.SH NAME
hostgen - generate randomized system hostnames mimicking various platforms
.SH SYNOPSIS
.B hostgen
[\fIOPTIONS\fR]...
.SH OPTIONS
.TP
\fB\-a, \-\-append\fR
Append to FILE, instead of overwriting or performing substitution in it.
.TP
\fB\-h, \-\-help\fR
Print a help message displaying the available options and platforms.
.TP
\fB\-o, \-\-names\fR=\fI\,NAMEFILE\/\fR
Choose a custom list of first names, rather than the list in "names.h" embedded into the program at compile time.
.TP
\fB\-o, \-\-output\fR=\fI\,FILE\/\fR
Specify which file to overwrite/append the generated hostname to instead of stdout.
.TP
\fB\-p, \-\-platform\fR=\fI\,PLATFORM\/\fR
Pick a hostname resembling a default for \fIPLATFORM\fR. See
.TP
\fB\-P, \-\-prefix\fR=\fI\,PREFIX\/\fR
Specify an arbitrary string to prepend to hostname(s).
.TP
\fB\-s, \-\-suffix\fR=\fI\,SUFFIX\/\fR
Specify an arbitrary string to append to hostname(s).
.TP
\fB\-v, \-\-version\fR
Print the version information.
.B SUPPORTED PLATFORMS
for more information.
.SH SUPPORTED PLATFORMS
.TP
.B mac\fR, \fBmacos\fR, \fBosx\fR
Alias to either \fBmacbook\fR or \fBmacmini\fR, random at runtime.
.TP
.B macbook
Generate a hostname like \fI[Name]s-Macbook-[Product]\fR, where \fI'Name'\fR represents a random first name and \fI'Product'\fR is either \fIAir\fR or \fIPro\fR.
.TP
.B macmini
Generate a hostname like \fI[Name]s-Mac-Mini\fR, where \fI'Name'\fR represents a random first name.
.TP
.B windows
Generate a hostname like \fI'DESKTOP-XXXXXXX'\fR, where each \fIX\fR represents a random alphanumeric character.
.TP
.B win7
Alias to \fBwindows\fR.
.TP
.B win8
Alias to \fBwindows\fR.
.TP
.B win10
Alias to \fBwindows\fR.
.TP
.B win11
Alias to \fBwindows\fR.
.SH EXAMPLES
(placeholder)
.SH AUTHORS
Written by Andrew Blue.
.SH SEE ALSO
\fBmacchanger\fR(1)
